"""
Reproducibility helpers.

Phase 12 MVP: for any fetched result, emit two artefacts that let a
third party re-run the query on their own machine:

  1. **Provenance JSON** — a STAC-lite record describing the query
     (source, params, dates, AOI summary, row/column counts,
     dataset attribution, generated_at). Small enough to bundle
     inside a shapefile or attach to a report.
  2. **Standalone Jupyter notebook** — Python cells that re-authenticate
     to Earth Engine, re-run the same fetch, and write a CSV. Ships as
     a `.ipynb` string so the Streamlit UI can offer it as a download.

These artefacts don't need a running API server — they document a
single fetch in a portable way. A full REST API + STAC catalog is a
larger deployment concern and is intentionally out of scope for this
in-app phase.
"""

from __future__ import annotations

import json
from datetime import datetime
from typing import Any, Dict, List, Optional


def build_provenance_record(
    *,
    source: str,
    parameters: Optional[List[str]] = None,
    dataset: Optional[str] = None,
    start_date: Optional[str] = None,
    end_date: Optional[str] = None,
    year: Optional[int] = None,
    year_to: Optional[int] = None,
    temporal_resolution: Optional[str] = None,
    n_locations: Optional[int] = None,
    n_polygons: Optional[int] = None,
    n_rows: Optional[int] = None,
    columns: Optional[List[str]] = None,
    attribution: Optional[str] = None,
    aoi_summary: Optional[Dict[str, Any]] = None,
    extra: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """Assemble a self-contained STAC-lite dict describing this fetch."""
    rec: Dict[str, Any] = {
        "spec_version": "1.0",
        "generated_at": datetime.utcnow().isoformat() + "Z",
        "source": source,
        "dataset": dataset,
        "parameters": parameters or [],
        "temporal": {
            "resolution": temporal_resolution,
            "start_date": start_date,
            "end_date": end_date,
            "year": year,
            "year_to": year_to,
        },
        "aoi": aoi_summary or {},
        "counts": {
            "rows": n_rows,
            "locations": n_locations,
            "polygons": n_polygons,
        },
        "columns": columns or [],
        "attribution": attribution,
    }
    if extra:
        rec["extra"] = extra
    return rec


def _cell_code(text: str) -> Dict[str, Any]:
    return {
        "cell_type": "code",
        "metadata": {},
        "source": text.splitlines(keepends=True),
        "outputs": [],
        "execution_count": None,
    }


def _cell_md(text: str) -> Dict[str, Any]:
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": text.splitlines(keepends=True),
    }


def build_reproduction_notebook(provenance: Dict[str, Any]) -> str:
    """Return a JSON string representing a self-contained ipynb that
    re-runs the fetch described by `provenance`.

    Every source in the app takes the same-shaped fetch call signature
    (locations + parameters + start_date + end_date + temporal_resolution
    + credentials_dict for point-based sources; aoi_gdf + parameters +
    credentials_dict for polygon-based sources). The notebook cells cover
    both patterns and let the reader pick the one that matches.
    """
    src = provenance.get("source", "")
    dataset = provenance.get("dataset") or "n/a"
    params = provenance.get("parameters") or []
    temporal = provenance.get("temporal") or {}
    attribution = provenance.get("attribution") or ""

    header_md = f"""# Reproducibility notebook

Auto-generated by the Weather Data Portal.

**Source:** {src}
**Dataset:** {dataset}
**Temporal:** {temporal.get('resolution')}  {temporal.get('start_date')} to {temporal.get('end_date')}
**Parameters:** {', '.join(params) if params else 'n/a'}

**Attribution:** {attribution}
"""

    prov_cell = "PROVENANCE = " + json.dumps(provenance, indent=2, default=str) + "\n"

    setup_cell = """import json
from data_sources import (
    nasa_power, era5, chirps, modis, drought_indices, phenology, soil_moisture,
    productivity, air_quality, lulc, hydrology, land_degradation, forest_biomass,
    africa_stack, population,
)

with open('ee_credentials.json') as f:
    ee_credentials = json.load(f)
"""

    fetch_cell = """# Locations either as (lat, lon) tuples for the point-based sources ...
locations = [
    # (latitude, longitude),
]

# ... or as a GeoDataFrame for polygon-based sources (LULC, hydrology,
# forest, africa, population, land_degradation, forest_biomass).
# import geopandas as gpd
# aoi_gdf = gpd.read_file('your_polygons.shp')

# Point-based source example (uncomment and adapt):
# df = era5.fetch_era5_data(
#     locations=locations,
#     parameters=PROVENANCE['parameters'],
#     start_date=PROVENANCE['temporal']['start_date'],
#     end_date=PROVENANCE['temporal']['end_date'],
#     temporal_resolution=PROVENANCE['temporal']['resolution'],
#     credentials_dict=ee_credentials,
# )

# Polygon-based source example (uncomment and adapt):
# df = hydrology.fetch_gsw_stats_from_gdf(
#     aoi_gdf=aoi_gdf,
#     dataset_name=PROVENANCE['dataset'],
#     credentials_dict=ee_credentials,
# )

# df.head()
"""

    export_cell = """# df.to_csv('reproduced_fetch.csv', index=False)"""

    nb = {
        "cells": [
            _cell_md(header_md),
            _cell_md("## 1. Provenance record"),
            _cell_code(prov_cell),
            _cell_md("## 2. Setup"),
            _cell_code(setup_cell),
            _cell_md("## 3. Re-run the fetch"),
            _cell_code(fetch_cell),
            _cell_md("## 4. Export"),
            _cell_code(export_cell),
        ],
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3", "language": "python", "name": "python3",
            },
            "language_info": {"name": "python"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    return json.dumps(nb, indent=1)
